services:
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: keeps
      POSTGRES_PASSWORD: keeps
      POSTGRES_DB: keeps
    ports:
      - "5432:5432"
    volumes:
      - pv_db:/var/lib/postgresql/data

  redis:
    image: redis:7
    ports:
      - "6379:6379"

  minio:
    image: minio/minio:latest
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: minio123456
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - pv_minio:/data

volumes:
  pv_db:
  pv_minio:
